### ISSUE TITLE
US_1.18: selection of filter

### ISSUE THREAD

**Issue by Helene0** [hpi-swt2/workshop-portal#141] opened 2016-12-05 18:57 UTC
**As** 
organizer and coach

**I want to** 
be able selecte from the sorted people (by status (angenommen, abgelehnt, [Nachrücker], and other properties) and only see angenommen, abgelehnt, [Nachrücker] or a combination of those

**in order to** 
get a better overview

** 🍪** 

Acceptance Criteria

 - [ ] I have a checkbox to choose if i want to see all different states of the application or only specific ones

**Comment by bjrne** [comment] 2017-01-04 12:03
duplicate of #116

**Closed by bjrne** 2017-01-04 12:03 UTC
Labels: Medium Priority, ready, team-helene
