### ISSUE TITLE
Refactor Event creation page

### ISSUE THREAD

**Issue by annkatrinkuessner** [hpi-swt2/workshop-portal#661] opened 2017-06-03 15:52 UTC
- [ ] Title and Description of an event should be mandatory information.  An admin should only be able to save an event if those information are provided. 
- [ ] Please indicate which fields are mandatory (Title, description, start and end date and application deadline )

**Comment by bjrne** [comment] 2017-08-09 15:35
Duplicate of #510

**Closed as completed by bjrne** 2017-08-09 15:35 UTC
Labels: Medium Priority
