### ISSUE TITLE
Requests Accessible By Unauthorized Users

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#351] opened 2017-01-18 15:08 UTC
sent requests are accessible without authentication via link (e.g. requests/2)
@hpi-swt2/scrum-master-2016

**Comment by bjrne** [comment] 2017-01-18 15:12
Duplicate of #346, I'll remove mine. This will be the main story.

**Comment by hendraet** [comment] 2017-01-18 15:16
Sorry for not checking for duplicates

**Closed as completed** 2017-01-27 10:18 UTC
Labels: bug
