### ISSUE TITLE
Application is not possible

### ISSUE THREAD

**Issue by tobiasduerschmid** [hpi-swt2/workshop-portal#480] opened 2017-02-02 08:12 UTC
When I apply for an event (on heroku) I get the error print: We're sorry, but something went wrong.

**Comment by Baschdl** [comment] 2017-02-02 13:08
Probable cause: #473

**Comment by Baschdl** [comment] 2017-02-02 15:33
I think #473 is not the cause

**Comment by cmfcmf** [comment] 2017-02-03 09:20
This is fixed by #487 and #490.

**Closed as completed** 2017-02-03 12:25 UTC
Labels: High Priority
